DELETE http://localhost:8080/events/1/registration
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGVtYWlsLmNvbSIsImV4cCI6MTc0ODYxMjYxMiwidXNlcklkIjozfQ.757DY8No5XfEf7lM3R8ib46vSeNDDdAgYdz8eB9FRV4