GET http://localhost:8080/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzQ4NjA4MzI0LCJ1c2VySWQiOjB9.J-ewSN35GUgzkMPvhr7SOboRcxHxd3Oh3I2uqIVlhs8
